export const browserCoreExamples = [
  "mrhammadclaw browser status",
  "mrhammadclaw browser start",
  "mrhammadclaw browser stop",
  "mrhammadclaw browser tabs",
  "mrhammadclaw browser open https://example.com",
  "mrhammadclaw browser focus abcd1234",
  "mrhammadclaw browser close abcd1234",
  "mrhammadclaw browser screenshot",
  "mrhammadclaw browser screenshot --full-page",
  "mrhammadclaw browser screenshot --ref 12",
  "mrhammadclaw browser snapshot",
  "mrhammadclaw browser snapshot --format aria --limit 200",
  "mrhammadclaw browser snapshot --efficient",
  "mrhammadclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "mrhammadclaw browser navigate https://example.com",
  "mrhammadclaw browser resize 1280 720",
  "mrhammadclaw browser click 12 --double",
  'mrhammadclaw browser type 23 "hello" --submit',
  "mrhammadclaw browser press Enter",
  "mrhammadclaw browser hover 44",
  "mrhammadclaw browser drag 10 11",
  "mrhammadclaw browser select 9 OptionA OptionB",
  "mrhammadclaw browser upload /tmp/mrhammadclaw/uploads/file.pdf",
  'mrhammadclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mrhammadclaw browser dialog --accept",
  'mrhammadclaw browser wait --text "Done"',
  "mrhammadclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mrhammadclaw browser console --level error",
  "mrhammadclaw browser pdf",
];
